<a href="https://colab.research.google.com/github/Shiv5246N/Assignment/blob/main/Fraud_Detection_(credit_card).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
# importing the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
# last 5 rows of the dataset
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
7968,10980,1.284388,-0.013181,0.646174,0.198985,-0.568675,-0.526121,-0.448235,-0.167709,1.773223,...,-0.101868,-0.030298,-0.081412,-0.123281,0.278808,1.064001,-0.090181,0.000481,15.95,0.0
7969,10981,1.190428,-0.122329,0.954945,0.267101,-0.971026,-0.652279,-0.612992,-0.003909,1.633117,...,-0.015001,0.127027,0.012079,0.534409,0.112179,1.004483,-0.100188,-0.004774,14.95,0.0
7970,10981,-0.725175,0.298202,1.824761,-2.587170,0.283605,-0.016617,0.153659,0.045084,-0.197611,...,-0.017097,-0.070535,-0.442861,-0.895837,0.624743,-0.510601,-0.031142,0.025564,12.95,0.0
7971,10981,1.226153,-0.129645,0.735197,0.142752,-0.703245,-0.349641,-0.612641,0.020507,1.648986,...,-0.047936,0.040196,-0.057391,-0.012386,0.187685,1.037786,-0.100081,-0.009869,15.95,0.0
7972,10981,1.145381,-0.059349,0.968088,0.267891,-0.822582,-0.597727,-0.450197,-0.119747,1.338188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7973 entries, 0 to 7972
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    7973 non-null   int64
 1   V1      7973 non-null   float64
 2   V2      7973 non-null   float64
 3   V3      7973 non-null   float64
 4   V4      7973 non-null   float64
 5   V5      7973 non-null   float64
 6   V6      7973 non-null   float64
 7   V7      7973 non-null   float64
 8   V8      7973 non-null   float64
 9   V9      7973 non-null   float64
 10  V10     7973 non-null   float64
 11  V11     7973 non-null   float64
 12  V12     7973 non-null   float64
 13  V13     7973 non-null   float64
 14  V14     7973 non-null   float64
 15  V15     7972 non-null   float64
 16  V16     7972 non-null   float64
 17  V17     7972 non-null   float64
 18  V18     7972 non-null   float64
 19  V19     7972 non-null   float64
 20  V20     7972 non-null   float64
 21  V21     7972 non-null   float64
 22  V22     7972 non-null   float64
 23  V23     7972 non-null   float64
 24  V24     7972 non-null   float64
 25  V25     7972 non-null   float64
 26  V26     7972 non-null   float64
 27  V27     7972 non-null   float64
 28  V28     7972 non-null   float64
 29  Amount  7972 non-null   float64
 30  Class   7972 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 1.9 MB

In [ ]:
# checking the missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
# distribution of legit transactions & fraudlent transactions
credit_card_data['Class'].value_counts()

Class
0.0    7947
1.0      25
Name: count, dtype: int64

This dataset is highly unbalanced

0-->Normal Transactions

1-->fraudlent Transactions

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(7947, 31)
(25, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    7947.000000
mean       65.284891
std       194.126547
min         0.000000
25%         4.795000
50%        15.950000
75%        54.990000
max      7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      25.000000
mean      106.308400
std       372.676883
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare the values of both the transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4246.546496,-0.297235,0.286979,0.917142,0.201968,-0.023263,0.164019,-0.019547,-0.072779,0.662196,...,0.042418,-0.055123,-0.165485,-0.034918,0.026636,0.088960,0.019511,0.014875,0.000417,65.284891
1.0,7359.240000,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.237600,106.308400

Under Sampling

Build a sample dataset containing similar distribution of normal transactions and fraudulent transactions

Number of Fraudulent Transactions --> 25

In [ ]:
legit_sample = legit.sample(n=25)

Concatenating two DataFrames

In [ ]:
new_dataset = pd.concat([legit_sample , fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
5742,6089,1.240352,0.198939,0.196200,0.310235,-0.314732,-1.269358,0.256118,-0.395832,1.244388,...,-0.577156,-1.552108,0.193388,0.322892,0.058668,0.581513,-0.135195,0.002464,39.98,0.0
7590,10491,-0.582934,0.676985,1.561897,-0.992154,0.092435,-0.277017,0.397509,0.081898,1.494243,...,-0.174994,-0.005530,-0.220536,0.013778,-0.181195,0.865050,0.249246,0.161090,4.06,0.0
137,84,-0.481376,1.003407,0.906184,-0.423864,0.760671,0.377627,0.587373,0.133884,-0.207871,...,-0.277507,-0.752696,-0.145992,-1.353515,-0.095516,0.175811,0.144228,0.099683,4.99,0.0
1147,894,-1.496310,0.033485,0.417450,-0.833103,1.185613,-0.126954,-0.231442,0.704543,-0.219157,...,-0.130690,-0.703806,-0.268196,-1.366119,-0.012137,0.375532,0.185834,-0.057046,1.00,0.0
4835,4329,-0.646542,0.937243,-0.255297,-1.020413,3.358665,3.045968,0.651913,0.659885,0.304785,...,-0.110472,-0.316085,-0.376222,0.934045,0.715870,-0.477958,0.012964,0.075390,8.15,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
6870,8757,-1.863756,3.442644,-4.468260,2.805336,-2.118412,-2.332285,-4.261237,1.701682,-1.439396,...,0.667927,-0.516242,-0.012218,0.070614,0.058504,0.304883,0.418012,0.208858,1.00,1.0
6882,8808,-4.617217,1.695694,-3.114372,4.328199,-1.873257,-0.989908,-4.577265,0.472216,0.472017,...,0.481830,0.146023,0.117039,-0.217565,-0.138776,-0.424453,-1.002041,0.890780,1.10,1.0
6899,8878,-2.661802,5.856393,-7.653616,6.379742,-0.060712,-3.131550,-3.103570,1.778492,-3.831154,...,0.734775,-0.435901,-0.384766,-0.286016,1.007934,0.413196,0.280284,0.303937,1.00,1.0
6903,8886,-2.535852,5.793644,-7.618463,6.395830,-0.065210,-3.136372,-3.104557,1.823233,-3.878658,...,0.716720,-0.448060,-0.402407,-0.288835,1.011752,0.425965,0.413140,0.308205,1.00,1.0
6971,9064,-3.499108,0.258555,-4.489558,4.853894,-6.974522,3.628382,5.431271,-1.946734,-0.775680,...,-1.052368,0.204817,-2.119007,0.170279,-0.393844,0.296367,1.985913,-0.900452,1809.68,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    25
1.0    25
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,3845.92,-0.498226,0.335515,0.612119,-0.007849,0.276982,0.617756,-0.023423,0.384968,0.556398,...,0.082899,-0.171114,-0.264615,0.070723,0.032456,0.111845,0.061497,0.030182,-0.09046,61.6024
1.0,7359.24,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.23760,106.3084

Splitting the data into Features and Targets

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

       Time        V1        V2        V3        V4        V5        V6  \
5742   6089  1.240352  0.198939  0.196200  0.310235 -0.314732 -1.269358
7590  10491 -0.582934  0.676985  1.561897 -0.992154  0.092435 -0.277017
137      84 -0.481376  1.003407  0.906184 -0.423864  0.760671  0.377627
1147    894 -1.496310  0.033485  0.417450 -0.833103  1.185613 -0.126954
4835   4329 -0.646542  0.937243 -0.255297 -1.020413  3.358665  3.045968
763     574 -0.402057  0.584300  2.474227  0.929684  0.014314  0.297490
5336   5252 -0.592605  1.135240  0.170209 -1.204934  3.100477  3.362828
1326   1039 -1.575524  0.053846  1.096594 -0.302090  0.193595 -1.463215
3702   3169 -0.730507  0.485490  2.220230  0.734363 -0.185446 -0.165816
5366   5311 -1.280425  1.534169 -0.736577 -0.973252  1.841376  3.296308
4707   4133  0.864737 -0.058892  0.412986  1.359236  0.581632  1.789744
4121   3744  1.406222 -0.675786 -0.912272 -1.618383  1.460758  3.273839
739     555 -0.953030  1.274549  1.835506  0.833734  0.019393 -0.103387
5736   6068  0.754685 -1.510803  1.323766  0.686392 -1.443216  1.480616
6958   9043 -5.839614  0.717285 -1.193202  0.868447 -0.596548 -1.691492
2420   1992 -0.388866  0.164614  2.525645  1.276530 -0.202505  1.560264
1617   1256 -2.594704  0.792116 -0.749193 -2.073082 -0.938225 -1.819945
1262    973 -0.869183  1.256710  0.926018  0.052778 -0.343745 -1.074462
7961  10979  1.270792 -0.466152  0.365816 -0.525627 -0.683161  0.022055
3741   3227 -1.453256  1.126475  1.024675  2.739288  0.663463  0.781161
4361   3763  1.388131 -0.385272  0.593833 -0.656869 -0.828618 -0.482989
240     160 -1.551482 -1.053346  0.762806  1.335129 -2.585523  1.942252
4232   3753  1.377746 -0.722841 -0.928800 -1.606410  1.446221  3.279144
5529   5606 -0.402733  1.097591  1.276895  0.028370  0.449224  0.042546
4026   3664  1.082841  0.188519 -0.012609  0.879773 -0.121573 -0.633302
541     406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623     472 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823
4920   4462 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788
6108   6986 -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536
6329   7519  1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746
6331   7526  0.008430  4.137837 -6.240697  6.675732  0.768307 -3.353060
6334   7535  0.026779  4.132464 -6.560600  6.348557  1.329666 -2.513479
6336   7543  0.329594  3.712889 -5.775935  6.078266  1.667359 -2.420168
6338   7551  0.316459  3.809076 -5.615159  6.047445  1.554026 -2.651353
6427   7610  0.725646  2.300894 -5.329976  4.007683 -1.730411 -1.732193
6446   7672  0.702710  2.426433 -5.234513  4.416661 -2.170806 -2.667554
6472   7740  1.023874  2.001485 -4.769752  3.819195 -1.271754 -1.734662
6529   7891 -1.585505  3.261585 -4.137422  2.357096 -1.405043 -1.879437
6609   8090 -1.783229  3.402794 -3.822742  2.625368 -1.976415 -2.731689
6641   8169  0.857321  4.093912 -7.423894  7.380245  0.973366 -2.730762
6717   8408 -1.813280  4.917851 -5.926130  5.701500  1.204393 -3.035138
6719   8415 -0.251471  4.313523 -6.891438  6.796797  0.616297 -2.966327
6734   8451  0.314597  2.660670 -5.920037  4.522500 -2.315027 -2.278352
6774   8528  0.447396  2.481954 -5.660814  4.455923 -2.443780 -2.185040
6820   8614 -2.169929  3.639654 -4.508498  2.730668 -2.122693 -2.341017
6870   8757 -1.863756  3.442644 -4.468260  2.805336 -2.118412 -2.332285
6882   8808 -4.617217  1.695694 -3.114372  4.328199 -1.873257 -0.989908
6899   8878 -2.661802  5.856393 -7.653616  6.379742 -0.060712 -3.131550
6903   8886 -2.535852  5.793644 -7.618463  6.395830 -0.065210 -3.136372
6971   9064 -3.499108  0.258555 -4.489558  4.853894 -6.974522  3.628382

            V7        V8        V9  ...       V20       V21       V22  \
5742  0.256118 -0.395832  1.244388  ... -0.064352 -0.577156 -1.552108
7590  0.397509  0.081898  1.494243  ... -0.043295 -0.174994 -0.005530
137   0.587373  0.133884 -0.207871  ...  0.082303 -0.277507 -0.752696
1147 -0.231442  0.704543 -0.219157  ...  0.233101 -0.130690 -0.703806
4835  0.651913  0.659885  0.304785  ... -0.060587 -0.110472 -0.316085
763   0.715195 -0.257153  0.593868  ... -0.026600 -0.072812  0.445733
5336  0.758997  0.012940  1.947706  ...  0.839271 -0.769764 -1.155971
1326 -0.163213  0.506951  0.082101  ...  0.098617 -0.081217 -0.585296
3702  0.262258  0.173131 -0.216593  ...  0.118551 -0.174177 -0.452334
5366 -0.680264  1.716256  0.617993  ...  0.081576 -0.379719 -1.136499
4707 -0.281837  0.476973  1.242440  ... -0.181540 -0.068057  0.247377
4121 -1.173726  0.711010  0.360405  ...  0.216919 -0.279639 -0.896927
739   0.833451 -0.242795 -0.075905  ...  0.237897 -0.143525  0.138945
5736 -1.404889  0.510527  3.377222  ...  0.265077 -0.030419  0.083407
6958 -1.297023  1.678671  1.862394  ... -2.037857 -1.212557 -0.551903
2420  0.188915 -0.007023  1.039315  ...  0.152423 -0.012045  0.658546
1617 -0.102909  1.103437  0.204788  ...  0.070067  0.173200  0.377772
1262  0.427422  0.247870  0.059041  ...  0.091996 -0.324417 -0.852459
7961 -1.011399  0.080285  0.447692  ...  0.114620  0.187797  0.684360
3741  0.597163  0.582689 -2.375165  ... -0.089981  0.175119  0.539275
4361 -0.752050 -0.103825  0.280984  ...  0.045725 -0.216137 -0.537549
240   1.646687  0.641266 -0.649862  ...  1.433397  0.867609  1.254201
4232 -1.154167  0.707184  0.358669  ...  0.246937 -0.270707 -0.904707
5529  0.412104  0.179791  0.722852  ...  0.033768 -0.360905 -0.749781
4026 -0.067756 -0.278361  1.413616  ...  0.214446 -0.014661  0.108652
541  -2.537387  1.391657 -2.770089  ...  0.126911  0.517232 -0.035049
623   0.325574 -0.067794 -0.270953  ...  2.102339  0.661696  0.435477
4920  0.562320 -0.399147 -0.238253  ... -0.430022 -0.294166 -0.932391
6108 -3.496197 -0.248778 -0.247768  ... -0.171608  0.573574  0.176968
6329  1.713445 -0.496358 -1.282858  ...  0.009061 -0.379068 -0.704181
6331 -1.631735  0.154612 -2.795892  ...  0.488378  0.364514 -0.608057
6334 -1.689102  0.303253 -3.139409  ...  0.587743  0.370509 -0.576752
6336 -0.812891  0.133080 -2.214311  ...  0.269773  0.156617 -0.652450
6338 -0.746579  0.055586 -2.678679  ...  0.388307  0.208828 -0.511747
6427 -3.968593  1.063728 -0.486097  ...  0.504646  0.589669  0.109541
6446 -3.878088  0.911337 -0.166199  ...  0.422743  0.551180 -0.009802
6472 -3.059245  0.889805  0.415382  ...  0.204138  0.343283 -0.054196
6529 -3.513687  1.515607 -1.207166  ...  0.315957  0.501543 -0.546869
6609 -3.430559  1.413204 -0.776941  ...  0.364089  0.454032 -0.577526
6641 -1.496497  0.543015 -2.351190  ...  0.483303  0.375026  0.145400
6717 -1.713402  0.561257 -3.796354  ...  0.576656  0.615642 -0.406427
6719 -2.436653  0.489328 -3.371639  ...  0.632710  0.536892 -0.546126
6734 -4.684054  1.202270 -0.694696  ...  0.562706  0.743314  0.064038
6774 -4.716143  1.249803 -0.718326  ...  0.549613  0.756053  0.140168
6820 -4.235253  1.703538 -1.305279  ...  0.500779  0.645103 -0.503529
6870 -4.261237  1.701682 -1.439396  ...  0.360924  0.667927 -0.516242
6882 -4.577265  0.472216  0.472017  ... -0.039046  0.481830  0.146023
6899 -3.103570  1.778492 -3.831154  ...  0.399097  0.734775 -0.435901
6903 -3.104557  1.823233 -3.878658  ...  0.408704  0.716720 -0.448060
6971  5.431271 -1.946734 -0.775680  ... -3.042626 -1.052368  0.204817

           V23       V24       V25       V26       V27       V28   Amount
5742  0.193388  0.322892  0.058668  0.581513 -0.135195  0.002464    39.98
7590 -0.220536  0.013778 -0.181195  0.865050  0.249246  0.161090     4.06
137  -0.145992 -1.353515 -0.095516  0.175811  0.144228  0.099683     4.99
1147 -0.268196 -1.366119 -0.012137  0.375532  0.185834 -0.057046     1.00
4835 -0.376222  0.934045  0.715870 -0.477958  0.012964  0.075390     8.15
763  -0.245103  0.421234  0.049280 -0.388323 -0.329333 -0.386747    12.00
5336 -0.177512  0.864512  0.015040 -0.050100 -0.110386 -0.627978     0.89
1326 -0.030083  0.384132 -0.247678  0.289668  0.185017 -0.031658     1.00
3702 -0.024509  0.420871 -0.024621  0.478240  0.041265  0.076490    25.17
5366  0.067374  0.918285  0.038844  0.057297  0.105981  0.031146    11.99
4707 -0.022586 -1.046107  0.358004 -0.277442  0.055090 -0.000620    69.00
4121  0.083467  0.919892  0.357956 -0.508112 -0.019454  0.015001    39.44
739  -0.237129  0.562703 -0.068519 -0.540693 -0.627312 -0.550223    11.22
5736 -0.415483 -0.777707  0.262093  1.250000 -0.063340  0.027246   228.00
6958  2.095694  0.303058  0.636787  0.223168  1.073486 -0.726030     9.99
2420 -0.253275 -0.742250 -0.355782 -0.182775 -0.191612 -0.286516    75.37
1617  0.148204  0.587936  0.071497 -0.153507  0.262471 -0.081060     1.00
1262  0.048882  0.273927 -0.169705  0.057235  0.055106 -0.134962    12.99
7961 -0.147915 -0.403501  0.386381 -0.093228  0.015917  0.023723    39.00
3741  0.257358 -0.260057  0.399719  0.405095 -0.084682 -0.078765    67.46
4361  0.093359 -0.078782  0.218938 -0.516913 -0.021465  0.002858    10.00
240   1.572315 -0.356254 -0.210821 -0.229607 -0.205431  0.039258   700.00
4232  0.070475  0.920648  0.352544 -0.509684 -0.022239  0.017568    54.18
5529 -0.014446 -0.434524 -0.258721  0.067453  0.227017  0.074003     6.28
4026 -0.283460 -0.217686  0.499208  0.639697 -0.048636  0.054194   106.90
541  -0.465211  0.320198  0.044519  0.177840  0.261145 -0.143276     0.00
623   1.375966 -0.293803  0.279798 -0.145362 -0.252773  0.035764   529.00
4920  0.172726 -0.087330 -0.156114 -0.542628  0.039566 -0.153029   239.93
6108 -0.436207 -0.053502  0.252405 -0.657488 -0.827136  0.849573    59.00
6329 -0.656805 -1.632653  1.488901  0.566797 -0.010016  0.146793     1.00
6331 -0.539528  0.128940  1.488481  0.507963  0.735822  0.513574     1.00
6334 -0.669605 -0.759908  1.605056  0.540675  0.737040  0.496699     1.00
6336 -0.551572 -0.716522  1.415717  0.555265  0.530507  0.404474     1.00
6338 -0.583813 -0.219845  1.474753  0.491192  0.518868  0.402528     1.00
6427  0.601045 -0.364700 -1.843078  0.351909  0.594550  0.099372     1.00
6446  0.721698  0.473246 -1.959304  0.319476  0.600485  0.129305     1.00
6472  0.709654 -0.372216 -2.032068  0.366778  0.395171  0.020206     1.00
6529 -0.076584 -0.425550  0.123644  0.321985  0.264028  0.132817     1.00
6609  0.045967  0.461700  0.044146  0.305704  0.530981  0.243746     1.00
6641  0.240603 -0.234649 -1.004881  0.435832  0.618324  0.148469     1.00
6717 -0.737018 -0.279642  1.106766  0.323885  0.894767  0.569519     1.00
6719 -0.605240 -0.263743  1.539916  0.523574  0.891025  0.572741     1.00
6734  0.677842  0.083008 -1.911034  0.322188  0.620867  0.185030     1.00
6774  0.665411  0.131464 -1.908217  0.334808  0.748534  0.175414     1.00
6820 -0.000523  0.071696  0.092007  0.308498  0.552591  0.298954     1.00
6870 -0.012218  0.070614  0.058504  0.304883  0.418012  0.208858     1.00
6882  0.117039 -0.217565 -0.138776 -0.424453 -1.002041  0.890780     1.10
6899 -0.384766 -0.286016  1.007934  0.413196  0.280284  0.303937     1.00
6903 -0.402407 -0.288835  1.011752  0.425965  0.413140  0.308205     1.00
6971 -2.119007  0.170279 -0.393844  0.296367  1.985913 -0.900452  1809.68

[50 rows x 30 columns]

In [ ]:
print(Y)

5742    0.0
7590    0.0
137     0.0
1147    0.0
4835    0.0
763     0.0
5336    0.0
1326    0.0
3702    0.0
5366    0.0
4707    0.0
4121    0.0
739     0.0
5736    0.0
6958    0.0
2420    0.0
1617    0.0
1262    0.0
7961    0.0
3741    0.0
4361    0.0
240     0.0
4232    0.0
5529    0.0
4026    0.0
541     1.0
623     1.0
4920    1.0
6108    1.0
6329    1.0
6331    1.0
6334    1.0
6336    1.0
6338    1.0
6427    1.0
6446    1.0
6472    1.0
6529    1.0
6609    1.0
6641    1.0
6717    1.0
6719    1.0
6734    1.0
6774    1.0
6820    1.0
6870    1.0
6882    1.0
6899    1.0
6903    1.0
6971    1.0
Name: Class, dtype: float64

Split the data into Training data & Testing data

In [ ]:
X_train, X_test, Y_train , Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(50, 30) (40, 30) (10, 30)

Model Training

Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
# Training the Logistic Regression Method with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on training data : ', training_data_accuracy)

Accuracy on training data :  1.0

In [ ]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy on test data : ', test_data_accuracy)

Accuracy on test data :  0.8